name: "install-crane"
description: "Installs crane"
inputs:
  version:
    description: crane version to install
    default: latest
    required: true
runs:
  using: "composite"
  steps:
  - name: Install crane
    uses: reconcilerio/go-install-action@v1
    with:
      package: github.com/google/go-containerregistry/cmd/crane
      version: "${{ inputs.version }}"
      download-url-template: https://github.com/google/go-containerregistry/releases/download/${version}/go-containerregistry_$(echo "${os:0:1}" | tr '[:lower:]' '[:upper:]')${os:1}_${arch/amd64/x86_64}.tar.gz
      download-path-within-archive: crane
      output-dir: /usr/local/bin
